### ISSUE TITLE
just checking - is this an intended effect of the counting feature?

### ISSUE THREAD

**Issue by laika-cosmonaut** [UwUAroze/Snuggles#4]
![2BF5A337-E617-4C04-9DFB-B6A5D4A93B97](https://user-images.githubusercontent.com/71281295/230217129-f752aa05-daf9-4a0d-a3d6-391a734a1641.jpeg)

the bot is really cool btw, thanks for making it public :)

**Comment by UwUAroze** [comment]
If you're referring to the math stuff, yes.

> the bot is really cool btw, thanks for making it public :)

ty <3
